//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPOSITEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPOSITEUR()
        {
            this.OEUVRE = new HashSet<OEUVRE>();
        }
    
        public int idCompositeur { get; set; }
        public int idNation { get; set; }
        public int idStyle { get; set; }
        public string nomCompositeur { get; set; }
        public string prenomCompositeur { get; set; }
        public Nullable<int> anNais { get; set; }
        public Nullable<int> anMort { get; set; }
        public string remarque { get; set; }
    
        public virtual NATIONALITE NATIONALITE { get; set; }
        public virtual STYLE STYLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEUVRE> OEUVRE { get; set; }
    }
}
